name: bca_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  intl: any
  nepali_date_picker: ^6.0.2
  nepali_utils: ^3.0.8
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  timeago: ^3.7.0
  top_snackbar_flutter: ^3.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/

  
